### ISSUE TITLE
cftoken and cfuser values

### ISSUE THREAD

**Issue by robert1112** [centminmod/centminmod-fail2ban#1]
Hi George

In this file, I just replace these 2 places with key and email or I need to replace each <cfuser> and <cftoken> in the file? It is a bit confusing for non-coder. Thank you so much.

cftoken = put-your-API-key-here
cfuser = put-your-cloudflare-email-here

**Comment by centminmod** [comment]
as per https://github.com/centminmod/centminmod-fail2ban#cloudflare-v4-api

> Then edited **action.d/cloudflare.conf** and filled in cfuser and cftoken variables with Cloudflare account email and API Key which you can find in your My Account area. Restart fail2ban service for good measure.

**Comment by robert1112** [comment]
Hi @centminmod  Thanks for your reply. Just to double check. so for example I need to replace these variables, <cftoken> and <cfuser> too? Thanks for such nice tool.

```
actionban = curl -s -X POST "https://api.cloudflare.com/client/v4/user/firewall/access_rules/rules" \
            -H "X-Auth-Email: **<cfuser>**" \
            -H "X-Auth-Key: **<cftoken>**" \
            -H "Content-Type: application/json" \
            --data '{"mode":"block","configuration":{"target":"ip","value":"<ip>"},"notes":"Fail2Ban"}'
```

**Comment by centminmod** [comment]
no just

```
cftoken = put-your-API-key-here
cfuser = put-your-cloudflare-email-here
```

**Comment by robert1112** [comment]
Thank you George
